#!/bin/sh 
tmux new-session -s 'dev' -n 'ide' -d 'vim'
tmux split-window -v -p 10 -t 'dev'
tmux split-window -h -t 'dev'
tmux new-window -n shell
tmux select-window -t dev:1
tmux select-pane -t 1
tmux -2 attach-session -d 
